version: '3'
services:
  web:
    image: givup
    build: .  # Add build context
    ports:
      - "11000:3000"
    restart: always
    volumes:
      - .:/app  # Optional: for live code updates
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=production

volumes:
  node_modules: