name: Deploy Givup Next.js app to VPS

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ibrahimsikder/givup-app .

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag ibrahimsikder/givup-app:latest ibrahimsikder/givup-app:latest
          docker push ibrahimsikder/givup-app:latest

      - name: SSH to VPS and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ibrahimsikder/givup-app:latest
            docker stop givup-app || true
            docker rm givup-app || true
            docker run -d -p 1100:3000 --name givup-app ibrahimsikder/givup-app:latest
